const SecretQuote = () => {
    return (
        <section className='secretQuote'>
            YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH
            YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH YOUR BEST SOURCE FOR TRUTH
        </section>
    )
}

export default SecretQuote;